section.container-fluid.card
  p  NetBLog #{Netblog::VERSION}, a simple browser interface to maintenance logbook.
  p  Executable: /usr/local/bin/netblog
  p  Database location: dbserver2:5432/netlog
  p  Compiled with Crystal (#{Crystal::VERSION}) [#{Netblog.date}]
    | and Kemal Web Framework (#{Kemal::VERSION}). 
  p  Distributed under the MIT License,
    a href="http://opensource.org/licenses/MIT" http://opensource.org/licenses/MIT.
  p  Creater, maintainer: lebogan <lewis.bogan@comcast.net>
