section.container-fluid.card
  p  NetBLog #{Netblog::VERSION}, a simple browser interface to maintenance logbook
    | hosted on a PostgreSQL server.
  p  Compiled with Crystal (#{Crystal::VERSION}) [#{Netblog.date_stamp}]
    | and Kemal Web Framework (#{Kemal::VERSION}). 
  p  Distributed under the MIT License,
    a href="http://opensource.org/licenses/MIT" http://opensource.org/licenses/MIT.
  p  Creater, maintainer: lebogan <lewis.bogan@comcast.net>
