/nav.slang
/nav
div.collapse.navbar-collapse id="collapsibleNavbar"
  ul.navbar-nav
    li.nav-item
      a.nav-link.text-primary.active href="/logs" title="Logs" Logs
    li.nav-item
      a.nav-link.text-primary href="/search" title="Search" Search
    li.nav-item
      a.nav-link.text-primary href="/maintenance" title="Maintenance" Maintenance
    li.nav-item
      a.nav-link.text-primary href="/notes" title="Notes" Notes
